# Generated by Django 2.1.3 on 2018-11-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordbook',
            name='understanding_level',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
