# Generated by Django 2.1.3 on 2018-11-12 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wordbook', '0002_wordbook_understanding_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeGameContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('practice_game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wordbook.PracticeGameContext')),
                ('wordbook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wordbook.Wordbook')),
            ],
        ),
        migrations.AddField(
            model_name='multiplechoices',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wordbook.Question'),
        ),
        migrations.AddField(
            model_name='multiplechoices',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wordbook.Word'),
        ),
    ]
