# Generated by Django 2.1.3 on 2018-11-18 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wordbook', '0002_wordbook_understanding_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'multiplechoices',
            },
        ),
        migrations.CreateModel(
            name='PracticeGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('url', models.SlugField(max_length=60)),
                ('single_attempt', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practicegame',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('practice_game', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='wordbook.PracticeGame')),
                ('wordbook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wordbook.Wordbook')),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correct answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wordbook.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('practice_game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wordbook.PracticeGame')),
            ],
            options={
                'db_table': 'practicegamecontext',
            },
        ),
        migrations.AddField(
            model_name='multiplechoices',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wordbook.Question'),
        ),
        migrations.AddField(
            model_name='multiplechoices',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wordbook.Word'),
        ),
    ]
