# Generated by Django 2.1.3 on 2018-11-17 10:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wordbook', '0002_wordbook_understanding_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'multiplechoices',
            },
        ),
        migrations.CreateModel(
            name='PracticeGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('url', models.SlugField(max_length=60)),
                ('random_order', models.BooleanField(default=False)),
                ('max_questions', models.PositiveIntegerField(blank=True, null=True)),
                ('answers_at_end', models.BooleanField(default=False)),
                ('exam_paper', models.BooleanField(default=False)),
                ('single_attempt', models.BooleanField(default=False)),
                ('draft', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'practicegame',
            },
        ),
        migrations.CreateModel(
            name='PracticeGameContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('practice_game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wordbook.PracticeGame')),
            ],
            options={
                'db_table': 'practicegamecontext',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('practice_game', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='wordbook.PracticeGame')),
                ('wordbook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wordbook.Wordbook')),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Sitting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order', models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('question_list', models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('incorrect_questions', models.CharField(max_length=1024, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('current_score', models.IntegerField()),
                ('complete', models.BooleanField(default=False)),
                ('user_answers', models.TextField(blank=True, default='{}')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('practice_game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wordbook.PracticeGame')),
            ],
            options={
                'db_table': 'sitting',
            },
        ),
        migrations.AddField(
            model_name='multiplechoices',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wordbook.Question'),
        ),
        migrations.AddField(
            model_name='multiplechoices',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wordbook.Word'),
        ),
    ]
